### ISSUE TITLE
Where physically will czf-con 2019 be located?

### ISSUE THREAD

**Issue by daiyi** [czf-con/orga#19]
The Facts:

- !!con-west & czf-con will be located at UC Santa Cruz's Engineering buildings

Questions:

- Which specific space within the engineering buildings will we have the zinefest? 
- How will this influence how we will physically lay out the zinefest?

**Comment by daiyi** [comment]
Here are the notes from Lindsey (via !!con-west slack):

> So here's the current situation: we've been told that the engineering auditorium and the courtyard next to it are both available for the three proposed weekends.  That is our current most fleshed-out plan for space.  The eng auditorium is a standalone structure next to the two engineering buildings (Jack Baskin Engineering and Engineering 2) -- here is a map: http://maps.ucsc.edu/content/directions-baskin-engineering-complex

> So it would make sense for the zinefest to be located in one of the two engineering buildings.  We are also working on reserving the Simularium, which is a large classroom adjacent to the courtyard, but I expect we'd want to use that either as a quiet room or as an unconferencing space

> However, if CZF wants the Simularium, then they can have it and we'll find something else (most likely some smaller classrooms in Engineering 2) for quiet rooms and unconferencing.  Sound good? 

([reference](https://bangbangcon-west.slack.com/archives/CCC32PWFR/p1535563616000100?thread_ts=1534640905.000100&cid=CCC32PWFR))

**Comment by meldckn** [comment]
I think the outdoor courtyard between the two engineering buildings is our best bet if we want to stay in engineering. Every other space in engineering would be awkward for tabling (lecture-style seating or smallish conference rooms). But they do poster sessions and formal social lunch things in the courtyard fairly regularly. February can be iffy for rain though. Maybe we could find room in the budget for tents? (Probably better to have if it's sunny anyway). 

Otherwise, I think we'd have to go outside of engineering. Maybe the College 9/10 Multipurpose Room (large open floor space, about 5 min walk from engineering), or the Digital Arts Research Center (about 15 min trek from engineering), or even the Museum of Art and History in downtown Santa Cruz (where they hold the SC Zinefest). 

I think my vote is for the courtyard.

**Comment by meldckn** [comment]
(Simularium has built in lecture seats and tables, and would be hard to set up and navigate for zine tables imo. I like the idea of using it for unconferencing.)

**Comment by daiyi** [comment]
The courtyard sounds great! (especially if there's already a precedent for postering and socialing). 

Rain is a good consideration that hadn't occurred to me, I will create a last-minute tracker to keep an eye on the weather as the date draws near!

**Comment by meldckn** [comment]
Lindsey confirmed on Slack that they have the Courtyard reserved for 2/23-24. (I think we'll just be zinefesting on the 24th, and I don't think !!Con has anything in particular planned for the courtyard the day before, but it's reserved.) 

Looks like !!Con will be using the Baskin Auditorium (Baskin Engineering, rm 101) and the Simularium (Engineering 2, rm 180). The Courtyard is nicely in-between those spaces!
